package VMPackage;

import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JOptionPane;
import java.lang.Math;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Sara
 */
public class MaintainerControlPanelJFrame extends javax.swing.JFrame {

    static int coinstock10;
    static int coinstock20;
    static int coinstock50;
    static int coinstock1;

    static int drinkstock1;
    static int drinkstock2;
    static int drinkstock3;
    static int drinkstock4;
    static int drinkstock5;
    static int drinkstock6;

    static String drinkPrice1;
    static String drinkPrice2;
    static String drinkPrice3;
    static String drinkPrice4;
    static String drinkPrice5;
    static String drinkPrice6;

    double totalCash;

//    SETTERS
//    Set All Drinks Stock
    public void setDrinks1(int drink1) {
        MaintainerControlPanelJFrame.drinkstock1 = drink1;
    }

    public void setDrinks2(int drink2) {
        MaintainerControlPanelJFrame.drinkstock2 = drink2;
    }

    public void setDrinks3(int drink3) {
        MaintainerControlPanelJFrame.drinkstock3 = drink3;
    }

    public void setDrinks4(int drink4) {
        MaintainerControlPanelJFrame.drinkstock4 = drink4;
    }

    public void setDrinks5(int drink5) {
        MaintainerControlPanelJFrame.drinkstock5 = drink5;
    }

    public void setDrinks6(int drink6) {
        MaintainerControlPanelJFrame.drinkstock6 = drink6;
    }

    //    Set All Coins
    public void setCoin10(int coin10) {
        MaintainerControlPanelJFrame.coinstock10 = coin10;
    }

    public void setCoin20(int coin20) {
        MaintainerControlPanelJFrame.coinstock20 = coin20;
    }

    public void setCoin50(int coin50) {
        MaintainerControlPanelJFrame.coinstock50 = coin50;
    }

    public void setCoin1(int coin1) {
        MaintainerControlPanelJFrame.coinstock1 = coin1;
    }

//    GETTERS
//    Get All Drinks
    public static int getDrinks1() {
        return drinkstock1;
    }

    public static int getDrinks2() {
        return drinkstock2;
    }

    public static int getDrinks3() {
        return drinkstock3;
    }

    public static int getDrinks4() {
        return drinkstock4;
    }

    public static int getDrinks5() {
        return drinkstock5;
    }

    public static int getDrinks6() {
        return drinkstock6;
    }

//    Get All Coins
    public static int getCoins10() {
        return coinstock10;
    }

    public static int getCoins20() {
        return coinstock20;
    }

    public static int getCoins50() {
        return coinstock50;
    }

    public static int getCoins1() {
        return coinstock1;
    }

    public MaintainerControlPanelJFrame() {
        initComponents();
//        DISABLE ALL BUTTONS BY DEFAULT
        totaldenomination10.setEnabled(false);
        totaldenomination20.setEnabled(false);
        totaldenomination50.setEnabled(false);
        totaldenomination1.setEnabled(false);
        DisplayDrinksStock.setEnabled(false);
        UpdateDrinksPrice.setEnabled(false);
        TotalCashHeld.setEnabled(false);
        CollectAllCash.setEnabled(false);
        Lock.setEnabled(false);
        GetNewDrink1Price.setEnabled(false);
        GetNewDrink2Price.setEnabled(false);
        GetNewDrink3Price.setEnabled(false);
        GetNewDrink4Price.setEnabled(false);
        GetNewDrink5Price.setEnabled(false);
        GetNewDrink6Price.setEnabled(false);
        PasswordInvalid.setEnabled(false);
        PasswordValid.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        totaldenomination10 = new javax.swing.JButton();
        totaldenomination20 = new javax.swing.JButton();
        totaldenomination1 = new javax.swing.JButton();
        totaldenomination50 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        CoinStock = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        InsertedPassword = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        DrinkStock1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        DrinkStock2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        DrinkStock3 = new javax.swing.JLabel();
        GetNewDrink1Price = new javax.swing.JTextField();
        GetNewDrink2Price = new javax.swing.JTextField();
        GetNewDrink3Price = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        DrinkStock4 = new javax.swing.JLabel();
        GetNewDrink4Price = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        DrinkStock5 = new javax.swing.JLabel();
        GetNewDrink5Price = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        DrinkStock6 = new javax.swing.JLabel();
        GetNewDrink6Price = new javax.swing.JTextField();
        DisplayDrinksStock = new javax.swing.JButton();
        UpdateDrinksPrice = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        TotalCashHeld = new javax.swing.JButton();
        TotalCash = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        CollectAllCash = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        Lock = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        PasswordInvalid = new javax.swing.JLabel();
        PasswordValid = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vending Machine Maintainer Panel");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("VIMTO SOFT DRINKS DISPENSER");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Number of Coins for each Denomination", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        totaldenomination10.setText("10c");
        totaldenomination10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totaldenomination10ActionPerformed(evt);
            }
        });

        totaldenomination20.setText("20c");
        totaldenomination20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totaldenomination20ActionPerformed(evt);
            }
        });

        totaldenomination1.setText("RM1");
        totaldenomination1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totaldenomination1ActionPerformed(evt);
            }
        });

        totaldenomination50.setText("50c");
        totaldenomination50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totaldenomination50ActionPerformed(evt);
            }
        });

        jLabel3.setText("Total Number of Coins in the Selected Denomination");

        CoinStock.setText("?");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(totaldenomination10)
                        .addGap(42, 42, 42)
                        .addComponent(totaldenomination20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totaldenomination50)
                        .addGap(41, 41, 41))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(92, 92, 92)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CoinStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totaldenomination1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totaldenomination10)
                    .addComponent(totaldenomination20)
                    .addComponent(totaldenomination1)
                    .addComponent(totaldenomination50))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CoinStock))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("INSERT PASSWORD");

        InsertedPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertedPasswordActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total Number of Cans", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel21.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel21.setText("Brand");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel22.setText("Stock");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel23.setText("New Price");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Blueberry");

        DrinkStock1.setText("?");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Raspberry");

        DrinkStock2.setText("?");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Passionfruit");

        DrinkStock3.setText("?");

        GetNewDrink1Price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetNewDrink1PriceActionPerformed(evt);
            }
        });

        GetNewDrink2Price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetNewDrink2PriceActionPerformed(evt);
            }
        });

        GetNewDrink3Price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetNewDrink3PriceActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Strawberry");

        DrinkStock4.setText("?");

        GetNewDrink4Price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetNewDrink4PriceActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Orange");

        DrinkStock5.setText("?");

        GetNewDrink5Price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetNewDrink5PriceActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Lime");

        DrinkStock6.setText("?");

        GetNewDrink6Price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetNewDrink6PriceActionPerformed(evt);
            }
        });

        DisplayDrinksStock.setText("Display Stock");
        DisplayDrinksStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayDrinksStockActionPerformed(evt);
            }
        });

        UpdateDrinksPrice.setText("Update Price");
        UpdateDrinksPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateDrinksPriceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DrinkStock1)
                            .addComponent(DrinkStock2)
                            .addComponent(DrinkStock3)
                            .addComponent(DrinkStock4)
                            .addComponent(DrinkStock5)
                            .addComponent(DrinkStock6)
                            .addComponent(jLabel22)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DisplayDrinksStock, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(GetNewDrink6Price, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(GetNewDrink5Price, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(GetNewDrink4Price, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(GetNewDrink3Price, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23)
                            .addComponent(GetNewDrink2Price, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(GetNewDrink1Price, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(UpdateDrinksPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(DrinkStock1)
                    .addComponent(GetNewDrink1Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(DrinkStock2)
                    .addComponent(GetNewDrink2Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(DrinkStock3)
                    .addComponent(GetNewDrink3Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(DrinkStock4)
                    .addComponent(GetNewDrink4Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GetNewDrink5Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DrinkStock5)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(DrinkStock6)
                    .addComponent(GetNewDrink6Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateDrinksPrice)
                    .addComponent(DisplayDrinksStock))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total Cash Held by the Machine", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        TotalCashHeld.setText("Press Here for Total Cash Held by the Machine");
        TotalCashHeld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalCashHeldActionPerformed(evt);
            }
        });

        TotalCash.setText("?");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TotalCashHeld)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TotalCash, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalCashHeld)
                    .addComponent(TotalCash))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cash Collection", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        CollectAllCash.setText("Collect All Cash");
        CollectAllCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CollectAllCashActionPerformed(evt);
            }
        });

        jLabel14.setText("Press Here to Collect All Cash");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(58, 58, 58)
                .addComponent(CollectAllCash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CollectAllCash)
                    .addComponent(jLabel14))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        submit.setText("submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Finish", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        Lock.setText("Finish");
        Lock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LockActionPerformed(evt);
            }
        });

        jLabel24.setText("Press Here when Finished");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Lock, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lock)
                    .addComponent(jLabel24))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        PasswordInvalid.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PasswordInvalid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PasswordInvalid.setText("PASSWORD INVALID");
        PasswordInvalid.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        PasswordValid.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PasswordValid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PasswordValid.setText("PASSWORD VALID");
        PasswordValid.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(PasswordValid, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PasswordInvalid, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(InsertedPassword)
                                .addGap(18, 18, 18)
                                .addComponent(submit)))
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InsertedPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordInvalid, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordValid, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setText("MAINTAINER CONTROL PANEL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertedPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertedPasswordActionPerformed
//NA
    }//GEN-LAST:event_InsertedPasswordActionPerformed

    private void DisplayDrinksStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayDrinksStockActionPerformed
        try {
            File myObj = new File("DrinksStock.txt");
            Scanner myReader = new Scanner(myObj);
            ArrayList<String> drinksStockList = new ArrayList<String>();
            while (myReader.hasNext()) {
                drinksStockList.add(myReader.next());
            }
            myReader.close();
            DrinkStock1.setText(String.valueOf(drinksStockList.get(1)));
            DrinkStock2.setText(String.valueOf(drinksStockList.get(3)));
            DrinkStock3.setText(String.valueOf(drinksStockList.get(5)));
            DrinkStock4.setText(String.valueOf(drinksStockList.get(7)));
            DrinkStock5.setText(String.valueOf(drinksStockList.get(9)));
            DrinkStock6.setText(String.valueOf(drinksStockList.get(11)));
        } catch (FileNotFoundException e) {
            System.out.println("An error occurred.");
            e.printStackTrace();

            DrinkStock1.setText("0");
            DrinkStock2.setText("0");
            DrinkStock3.setText("0");
            DrinkStock4.setText("0");
            DrinkStock5.setText("0");
            DrinkStock6.setText("0");
        }
    }//GEN-LAST:event_DisplayDrinksStockActionPerformed

    private void CollectAllCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CollectAllCashActionPerformed
        if (totalCash == 0) {
            JOptionPane.showMessageDialog(rootPane, "Sorry, the is no money in the machine!");
        } else {
            JOptionPane.showMessageDialog(rootPane, "A total cash of: " + totalCash + " has been dispensed. Please, collect!");
            totalCash = 0;
            TotalCash.setText(String.valueOf(totalCash));
            CoinStock.setText("?");
            //        RESET THE QUANTITY TO 0 IN THE FILE
            try {
                FileWriter myWriter = new FileWriter("CoinStock.txt");
                myWriter.write(
                        "coinsStock10 " + 0
                        + "\ncoinsStock20 " + 0
                        + "\ncoinsStock50 " + 0
                        + "\ncoinsStock-1 " + 0
                );
                myWriter.close();
                System.out.println("Successfully reset stock of coins in CoinStock.txt file.");
            } catch (IOException e) {
                System.out.println("An error occurred.");
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_CollectAllCashActionPerformed

    private void totaldenomination1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totaldenomination1ActionPerformed
        try {
            File myObj = new File("CoinStock.txt");
            Scanner myReader = new Scanner(myObj);
            ArrayList<String> coinsStockList = new ArrayList<String>();
            while (myReader.hasNext()) {
                coinsStockList.add(myReader.next());
            }
            myReader.close();

            CoinStock.setText(String.valueOf(coinsStockList.get(7)));

        } catch (FileNotFoundException e) {
            CoinStock.setText("0");
            System.out.println("An error occurred.");
            e.printStackTrace();
        }
    }//GEN-LAST:event_totaldenomination1ActionPerformed

    private void GetNewDrink2PriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetNewDrink2PriceActionPerformed
        // N/A
    }//GEN-LAST:event_GetNewDrink2PriceActionPerformed

    private void GetNewDrink3PriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetNewDrink3PriceActionPerformed
        // N/A
    }//GEN-LAST:event_GetNewDrink3PriceActionPerformed

    private void GetNewDrink4PriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetNewDrink4PriceActionPerformed
        // N/A
    }//GEN-LAST:event_GetNewDrink4PriceActionPerformed

    private void GetNewDrink5PriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetNewDrink5PriceActionPerformed
        // N/A
    }//GEN-LAST:event_GetNewDrink5PriceActionPerformed

    private void GetNewDrink6PriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetNewDrink6PriceActionPerformed
        // N/A
    }//GEN-LAST:event_GetNewDrink6PriceActionPerformed

    private void UpdateDrinksPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateDrinksPriceActionPerformed
        //    GET TEXT FROM INPUT FIELD
        drinkPrice1 = GetNewDrink1Price.getText();
        drinkPrice2 = GetNewDrink2Price.getText();
        drinkPrice3 = GetNewDrink3Price.getText();
        drinkPrice4 = GetNewDrink4Price.getText();
        drinkPrice5 = GetNewDrink5Price.getText();
        drinkPrice6 = GetNewDrink6Price.getText();

        if (JavaChecker.stringIsNull(drinkPrice1) == true || JavaChecker.stringIsNull(drinkPrice2) == true || JavaChecker.stringIsNull(drinkPrice3) == true || JavaChecker.stringIsNull(drinkPrice4) == true || JavaChecker.stringIsNull(drinkPrice5) == true || JavaChecker.stringIsNull(drinkPrice6) == true) {
            JOptionPane.showMessageDialog(rootPane, "Drinks Price value cannot be empty!");
        } else if (JavaChecker.isNumeric(drinkPrice1) == false || JavaChecker.isNumeric(drinkPrice2) == false || JavaChecker.isNumeric(drinkPrice3) == false || JavaChecker.isNumeric(drinkPrice4) == false || JavaChecker.isNumeric(drinkPrice5) == false || JavaChecker.isNumeric(drinkPrice6) == false) {
            JOptionPane.showMessageDialog(rootPane, "Invalid price value! Please only insert a number.");
        } else if (Double.parseDouble(drinkPrice1) < 0 || Double.parseDouble(drinkPrice2) < 0 || Double.parseDouble(drinkPrice3) < 0 || Double.parseDouble(drinkPrice4) < 0 || Double.parseDouble(drinkPrice5) < 0 || Double.parseDouble(drinkPrice6) < 0) {
            JOptionPane.showMessageDialog(rootPane, "Invalid price value! Please only insert positive number.");
        } else {
//            Round-up
            drinkPrice1 = String.valueOf(JavaChecker.roundUp(drinkPrice1));
            drinkPrice2 = String.valueOf(JavaChecker.roundUp(drinkPrice2));
            drinkPrice3 = String.valueOf(JavaChecker.roundUp(drinkPrice3));
            drinkPrice4 = String.valueOf(JavaChecker.roundUp(drinkPrice4));
            drinkPrice5 = String.valueOf(JavaChecker.roundUp(drinkPrice5));
            drinkPrice6 = String.valueOf(JavaChecker.roundUp(drinkPrice6));

//      FILES
//      WRITE VALUES INSERTED INTO THE DrinksStock.txt file
            try {
                FileWriter myWriter = new FileWriter("DrinksPrice.txt");
                myWriter.write(
                        "drinkPrice1 " + drinkPrice1
                        + "\ndrinkPrice2 " + drinkPrice2
                        + "\ndrinkPrice3 " + drinkPrice3
                        + "\ndrinkPrice4 " + drinkPrice4
                        + "\ndrinkPrice5 " + drinkPrice5
                        + "\ndrinkPrice6 " + drinkPrice6
                );
                myWriter.close();
                System.out.println("Successfully wrote to the file.");
            } catch (IOException e) {
                System.out.println("An error occurred.");
                e.printStackTrace();
            }
            JOptionPane.showMessageDialog(rootPane, "Price Updated Successfully!");
        }
    }//GEN-LAST:event_UpdateDrinksPriceActionPerformed

    private void GetNewDrink1PriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetNewDrink1PriceActionPerformed
        // N/A
    }//GEN-LAST:event_GetNewDrink1PriceActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        String password = "123456";
        String insertedPassword = InsertedPassword.getText();
        if (insertedPassword.equals(password)) {
            JOptionPane.showMessageDialog(rootPane, "Correct Password. Door Unclocked & Maintainer Access Granted.");
            totaldenomination10.setEnabled(true);
            totaldenomination20.setEnabled(true);
            totaldenomination50.setEnabled(true);
            totaldenomination1.setEnabled(true);
            DisplayDrinksStock.setEnabled(true);
            UpdateDrinksPrice.setEnabled(true);
            TotalCashHeld.setEnabled(true);
            CollectAllCash.setEnabled(true);
            Lock.setEnabled(true);
            GetNewDrink1Price.setEnabled(true);
            GetNewDrink2Price.setEnabled(true);
            GetNewDrink3Price.setEnabled(true);
            GetNewDrink4Price.setEnabled(true);
            GetNewDrink5Price.setEnabled(true);
            GetNewDrink6Price.setEnabled(true);
            PasswordValid.setEnabled(true);
            PasswordValid.setForeground(Color.GREEN);
            PasswordInvalid.setEnabled(false);
        } else if (!insertedPassword.equals(password)) {
            JOptionPane.showMessageDialog(rootPane, "Incorrect Password!");
            PasswordInvalid.setEnabled(true);
            PasswordInvalid.setForeground(Color.red);
            PasswordValid.setEnabled(false);
        }
    }//GEN-LAST:event_submitActionPerformed

    private void LockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LockActionPerformed
        totaldenomination10.setEnabled(false);
        totaldenomination20.setEnabled(false);
        totaldenomination50.setEnabled(false);
        totaldenomination1.setEnabled(false);
        DisplayDrinksStock.setEnabled(false);
        UpdateDrinksPrice.setEnabled(false);
        TotalCashHeld.setEnabled(false);
        CollectAllCash.setEnabled(false);
        Lock.setEnabled(false);
        GetNewDrink1Price.setEnabled(false);
        GetNewDrink2Price.setEnabled(false);
        GetNewDrink3Price.setEnabled(false);
        GetNewDrink4Price.setEnabled(false);
        GetNewDrink5Price.setEnabled(false);
        GetNewDrink6Price.setEnabled(false);
        PasswordInvalid.setEnabled(false);
        PasswordValid.setEnabled(false);
    }//GEN-LAST:event_LockActionPerformed

    private void totaldenomination10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totaldenomination10ActionPerformed

        try {
            File myObj = new File("CoinStock.txt");
            Scanner myReader = new Scanner(myObj);
            ArrayList<String> coinsStockList = new ArrayList<String>();
            while (myReader.hasNext()) {
                coinsStockList.add(myReader.next());
            }
            myReader.close();
            CoinStock.setText(String.valueOf(coinsStockList.get(1)));
        } catch (FileNotFoundException e) {
            System.out.println("An error occurred.");
            e.printStackTrace();

            CoinStock.setText("0");
        }

    }//GEN-LAST:event_totaldenomination10ActionPerformed

    private void totaldenomination20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totaldenomination20ActionPerformed
        try {
            File myObj = new File("CoinStock.txt");
            Scanner myReader = new Scanner(myObj);
            ArrayList<String> coinsStockList = new ArrayList<String>();
            while (myReader.hasNext()) {
                coinsStockList.add(myReader.next());
            }
            myReader.close();
            CoinStock.setText(String.valueOf(coinsStockList.get(3)));
        } catch (FileNotFoundException e) {
            System.out.println("An error occurred.");
            e.printStackTrace();
            CoinStock.setText("0");
        }
    }//GEN-LAST:event_totaldenomination20ActionPerformed

    private void totaldenomination50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totaldenomination50ActionPerformed
        try {
            File myObj = new File("CoinStock.txt");
            Scanner myReader = new Scanner(myObj);
            ArrayList<String> coinsStockList = new ArrayList<String>();
            while (myReader.hasNext()) {
                coinsStockList.add(myReader.next());
            }
            myReader.close();
            CoinStock.setText(String.valueOf(coinsStockList.get(5)));

        } catch (FileNotFoundException e) {
            CoinStock.setText("0");
            System.out.println("An error occurred.");
            e.printStackTrace();
        }
    }//GEN-LAST:event_totaldenomination50ActionPerformed

    private void TotalCashHeldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalCashHeldActionPerformed
        try {
            File myObj = new File("CoinStock.txt");
            Scanner myReader = new Scanner(myObj);
            ArrayList<String> coinStockList = new ArrayList<String>();
            while (myReader.hasNext()) {
                coinStockList.add(myReader.next());
            }
            myReader.close();

            double coinstomoney10 = Double.parseDouble(coinStockList.get(1)) * 0.1;
            double coinstomoney20 = Double.parseDouble(coinStockList.get(3)) * 0.2;
            double coinstomoney50 = Double.parseDouble(coinStockList.get(5)) * 0.5;
            double coinstomoney1 = Double.parseDouble(coinStockList.get(7)) * 1;
            totalCash = coinstomoney10 + coinstomoney20 + coinstomoney50 + coinstomoney1;
            TotalCash.setText(String.valueOf(totalCash));
        } catch (FileNotFoundException e) {
            TotalCash.setText("0");
            System.out.println("An error occurred.");
            e.printStackTrace();
        }
    }//GEN-LAST:event_TotalCashHeldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimulatorControlPanelJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimulatorControlPanelJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimulatorControlPanelJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimulatorControlPanelJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimulatorControlPanelJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CoinStock;
    private javax.swing.JButton CollectAllCash;
    private javax.swing.JButton DisplayDrinksStock;
    private javax.swing.JLabel DrinkStock1;
    private javax.swing.JLabel DrinkStock2;
    private javax.swing.JLabel DrinkStock3;
    private javax.swing.JLabel DrinkStock4;
    private javax.swing.JLabel DrinkStock5;
    private javax.swing.JLabel DrinkStock6;
    private javax.swing.JTextField GetNewDrink1Price;
    private javax.swing.JTextField GetNewDrink2Price;
    private javax.swing.JTextField GetNewDrink3Price;
    private javax.swing.JTextField GetNewDrink4Price;
    private javax.swing.JTextField GetNewDrink5Price;
    private javax.swing.JTextField GetNewDrink6Price;
    private javax.swing.JTextField InsertedPassword;
    private javax.swing.JButton Lock;
    private javax.swing.JLabel PasswordInvalid;
    private javax.swing.JLabel PasswordValid;
    private javax.swing.JLabel TotalCash;
    private javax.swing.JButton TotalCashHeld;
    private javax.swing.JButton UpdateDrinksPrice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JButton submit;
    private javax.swing.JButton totaldenomination1;
    private javax.swing.JButton totaldenomination10;
    private javax.swing.JButton totaldenomination20;
    private javax.swing.JButton totaldenomination50;
    // End of variables declaration//GEN-END:variables
}
